// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessLog struct {
	ID              pgtype.UUID
	Ip              string
	Method          string
	Endpoint        pgtype.Text
	RequestBody     pgtype.Text
	RequestHeaders  pgtype.Text
	RequestQuery    pgtype.Text
	RequestParams   pgtype.Text
	ResponseBody    pgtype.Text
	ResponseHeaders pgtype.Text
	ResponseTime    pgtype.Text
	StatusCode      pgtype.Int4
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type Client struct {
	ID        pgtype.UUID
	Name      string
	Cnpj      string
	Role      pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Emission struct {
	ID           pgtype.UUID
	EmissionType string
	ClientID     pgtype.UUID
	Message      pgtype.Text
	Status       pgtype.Text
	UserID       pgtype.UUID
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type File struct {
	ID          pgtype.UUID
	FileName    string
	Extension   string
	ContentType string
	FilePath    string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type GnreEmission struct {
	ID             pgtype.UUID
	Xml            pgtype.UUID
	Pdf            pgtype.UUID
	ComprovantePdf pgtype.UUID
	GuiaAmount     pgtype.Numeric
	NumeroRecibo   pgtype.Text
	ChaveNota      string
	CodBarrasGuia  pgtype.Text
	NumNota        string
	Destinatario   string
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Password  string
	ApiKey    string
	Role      pgtype.Text
	ClientID  pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
