services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file: .env
    environment:
      - TYPE=api
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - contafacil_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file: .env
    environment:
      - TYPE=worker
    deploy:
      replicas: 1
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - contafacil_network

  asynqmon:
    container_name: asynqmon
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: sua_senha
      BASIC_AUTH_USER: admin
      ASIC_AUTH_PASS: secret
    networks:
      - contafacil_network
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: contafacil
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - cf-data-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - contafacil_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - contafacil_network
    restart: unless-stopped

volumes:
  cf-data-postgres:
  redis-data:

networks:
  contafacil_network:
