// Code generated by ent, DO NOT EDIT.

package clients

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lucasbonna/contafacil_api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldName, v))
}

// Cnpj applies equality check predicate on the "cnpj" field. It's identical to CnpjEQ.
func Cnpj(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldCnpj, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContainsFold(FieldName, v))
}

// CnpjEQ applies the EQ predicate on the "cnpj" field.
func CnpjEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldCnpj, v))
}

// CnpjNEQ applies the NEQ predicate on the "cnpj" field.
func CnpjNEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldCnpj, v))
}

// CnpjIn applies the In predicate on the "cnpj" field.
func CnpjIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldCnpj, vs...))
}

// CnpjNotIn applies the NotIn predicate on the "cnpj" field.
func CnpjNotIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldCnpj, vs...))
}

// CnpjGT applies the GT predicate on the "cnpj" field.
func CnpjGT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldCnpj, v))
}

// CnpjGTE applies the GTE predicate on the "cnpj" field.
func CnpjGTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldCnpj, v))
}

// CnpjLT applies the LT predicate on the "cnpj" field.
func CnpjLT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldCnpj, v))
}

// CnpjLTE applies the LTE predicate on the "cnpj" field.
func CnpjLTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldCnpj, v))
}

// CnpjContains applies the Contains predicate on the "cnpj" field.
func CnpjContains(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContains(FieldCnpj, v))
}

// CnpjHasPrefix applies the HasPrefix predicate on the "cnpj" field.
func CnpjHasPrefix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasPrefix(FieldCnpj, v))
}

// CnpjHasSuffix applies the HasSuffix predicate on the "cnpj" field.
func CnpjHasSuffix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasSuffix(FieldCnpj, v))
}

// CnpjEqualFold applies the EqualFold predicate on the "cnpj" field.
func CnpjEqualFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEqualFold(FieldCnpj, v))
}

// CnpjContainsFold applies the ContainsFold predicate on the "cnpj" field.
func CnpjContainsFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContainsFold(FieldCnpj, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldRole, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Clients {
	return predicate.Clients(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Clients {
	return predicate.Clients(sql.FieldNotNull(FieldDeletedAt))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Clients {
	return predicate.Clients(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Clients {
	return predicate.Clients(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Clients) predicate.Clients {
	return predicate.Clients(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Clients) predicate.Clients {
	return predicate.Clients(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Clients) predicate.Clients {
	return predicate.Clients(sql.NotPredicates(p))
}
