// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lucasbonna/contafacil_api/ent/gnreemission"
	"github.com/lucasbonna/contafacil_api/ent/predicate"
)

// GnreEmissionDelete is the builder for deleting a GnreEmission entity.
type GnreEmissionDelete struct {
	config
	hooks    []Hook
	mutation *GnreEmissionMutation
}

// Where appends a list predicates to the GnreEmissionDelete builder.
func (ged *GnreEmissionDelete) Where(ps ...predicate.GnreEmission) *GnreEmissionDelete {
	ged.mutation.Where(ps...)
	return ged
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ged *GnreEmissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ged.sqlExec, ged.mutation, ged.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ged *GnreEmissionDelete) ExecX(ctx context.Context) int {
	n, err := ged.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ged *GnreEmissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gnreemission.Table, sqlgraph.NewFieldSpec(gnreemission.FieldID, field.TypeUUID))
	if ps := ged.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ged.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ged.mutation.done = true
	return affected, err
}

// GnreEmissionDeleteOne is the builder for deleting a single GnreEmission entity.
type GnreEmissionDeleteOne struct {
	ged *GnreEmissionDelete
}

// Where appends a list predicates to the GnreEmissionDelete builder.
func (gedo *GnreEmissionDeleteOne) Where(ps ...predicate.GnreEmission) *GnreEmissionDeleteOne {
	gedo.ged.mutation.Where(ps...)
	return gedo
}

// Exec executes the deletion query.
func (gedo *GnreEmissionDeleteOne) Exec(ctx context.Context) error {
	n, err := gedo.ged.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gnreemission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gedo *GnreEmissionDeleteOne) ExecX(ctx context.Context) {
	if err := gedo.Exec(ctx); err != nil {
		panic(err)
	}
}
