// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lucasbonna/contafacil_api/ent/emission"
	"github.com/lucasbonna/contafacil_api/ent/gnreemission"
	"github.com/lucasbonna/contafacil_api/ent/predicate"
)

// GnreEmissionQuery is the builder for querying GnreEmission entities.
type GnreEmissionQuery struct {
	config
	ctx          *QueryContext
	order        []gnreemission.OrderOption
	inters       []Interceptor
	predicates   []predicate.GnreEmission
	withEmission *EmissionQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GnreEmissionQuery builder.
func (geq *GnreEmissionQuery) Where(ps ...predicate.GnreEmission) *GnreEmissionQuery {
	geq.predicates = append(geq.predicates, ps...)
	return geq
}

// Limit the number of records to be returned by this query.
func (geq *GnreEmissionQuery) Limit(limit int) *GnreEmissionQuery {
	geq.ctx.Limit = &limit
	return geq
}

// Offset to start from.
func (geq *GnreEmissionQuery) Offset(offset int) *GnreEmissionQuery {
	geq.ctx.Offset = &offset
	return geq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (geq *GnreEmissionQuery) Unique(unique bool) *GnreEmissionQuery {
	geq.ctx.Unique = &unique
	return geq
}

// Order specifies how the records should be ordered.
func (geq *GnreEmissionQuery) Order(o ...gnreemission.OrderOption) *GnreEmissionQuery {
	geq.order = append(geq.order, o...)
	return geq
}

// QueryEmission chains the current query on the "emission" edge.
func (geq *GnreEmissionQuery) QueryEmission() *EmissionQuery {
	query := (&EmissionClient{config: geq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := geq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := geq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gnreemission.Table, gnreemission.FieldID, selector),
			sqlgraph.To(emission.Table, emission.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, gnreemission.EmissionTable, gnreemission.EmissionColumn),
		)
		fromU = sqlgraph.SetNeighbors(geq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GnreEmission entity from the query.
// Returns a *NotFoundError when no GnreEmission was found.
func (geq *GnreEmissionQuery) First(ctx context.Context) (*GnreEmission, error) {
	nodes, err := geq.Limit(1).All(setContextOp(ctx, geq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gnreemission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (geq *GnreEmissionQuery) FirstX(ctx context.Context) *GnreEmission {
	node, err := geq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GnreEmission ID from the query.
// Returns a *NotFoundError when no GnreEmission ID was found.
func (geq *GnreEmissionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = geq.Limit(1).IDs(setContextOp(ctx, geq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gnreemission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (geq *GnreEmissionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := geq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GnreEmission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GnreEmission entity is found.
// Returns a *NotFoundError when no GnreEmission entities are found.
func (geq *GnreEmissionQuery) Only(ctx context.Context) (*GnreEmission, error) {
	nodes, err := geq.Limit(2).All(setContextOp(ctx, geq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gnreemission.Label}
	default:
		return nil, &NotSingularError{gnreemission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (geq *GnreEmissionQuery) OnlyX(ctx context.Context) *GnreEmission {
	node, err := geq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GnreEmission ID in the query.
// Returns a *NotSingularError when more than one GnreEmission ID is found.
// Returns a *NotFoundError when no entities are found.
func (geq *GnreEmissionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = geq.Limit(2).IDs(setContextOp(ctx, geq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gnreemission.Label}
	default:
		err = &NotSingularError{gnreemission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (geq *GnreEmissionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := geq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GnreEmissions.
func (geq *GnreEmissionQuery) All(ctx context.Context) ([]*GnreEmission, error) {
	ctx = setContextOp(ctx, geq.ctx, ent.OpQueryAll)
	if err := geq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GnreEmission, *GnreEmissionQuery]()
	return withInterceptors[[]*GnreEmission](ctx, geq, qr, geq.inters)
}

// AllX is like All, but panics if an error occurs.
func (geq *GnreEmissionQuery) AllX(ctx context.Context) []*GnreEmission {
	nodes, err := geq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GnreEmission IDs.
func (geq *GnreEmissionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if geq.ctx.Unique == nil && geq.path != nil {
		geq.Unique(true)
	}
	ctx = setContextOp(ctx, geq.ctx, ent.OpQueryIDs)
	if err = geq.Select(gnreemission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (geq *GnreEmissionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := geq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (geq *GnreEmissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, geq.ctx, ent.OpQueryCount)
	if err := geq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, geq, querierCount[*GnreEmissionQuery](), geq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (geq *GnreEmissionQuery) CountX(ctx context.Context) int {
	count, err := geq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (geq *GnreEmissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, geq.ctx, ent.OpQueryExist)
	switch _, err := geq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (geq *GnreEmissionQuery) ExistX(ctx context.Context) bool {
	exist, err := geq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GnreEmissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (geq *GnreEmissionQuery) Clone() *GnreEmissionQuery {
	if geq == nil {
		return nil
	}
	return &GnreEmissionQuery{
		config:       geq.config,
		ctx:          geq.ctx.Clone(),
		order:        append([]gnreemission.OrderOption{}, geq.order...),
		inters:       append([]Interceptor{}, geq.inters...),
		predicates:   append([]predicate.GnreEmission{}, geq.predicates...),
		withEmission: geq.withEmission.Clone(),
		// clone intermediate query.
		sql:  geq.sql.Clone(),
		path: geq.path,
	}
}

// WithEmission tells the query-builder to eager-load the nodes that are connected to
// the "emission" edge. The optional arguments are used to configure the query builder of the edge.
func (geq *GnreEmissionQuery) WithEmission(opts ...func(*EmissionQuery)) *GnreEmissionQuery {
	query := (&EmissionClient{config: geq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	geq.withEmission = query
	return geq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		XML uuid.UUID `json:"xml,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GnreEmission.Query().
//		GroupBy(gnreemission.FieldXML).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (geq *GnreEmissionQuery) GroupBy(field string, fields ...string) *GnreEmissionGroupBy {
	geq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GnreEmissionGroupBy{build: geq}
	grbuild.flds = &geq.ctx.Fields
	grbuild.label = gnreemission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		XML uuid.UUID `json:"xml,omitempty"`
//	}
//
//	client.GnreEmission.Query().
//		Select(gnreemission.FieldXML).
//		Scan(ctx, &v)
func (geq *GnreEmissionQuery) Select(fields ...string) *GnreEmissionSelect {
	geq.ctx.Fields = append(geq.ctx.Fields, fields...)
	sbuild := &GnreEmissionSelect{GnreEmissionQuery: geq}
	sbuild.label = gnreemission.Label
	sbuild.flds, sbuild.scan = &geq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GnreEmissionSelect configured with the given aggregations.
func (geq *GnreEmissionQuery) Aggregate(fns ...AggregateFunc) *GnreEmissionSelect {
	return geq.Select().Aggregate(fns...)
}

func (geq *GnreEmissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range geq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, geq); err != nil {
				return err
			}
		}
	}
	for _, f := range geq.ctx.Fields {
		if !gnreemission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if geq.path != nil {
		prev, err := geq.path(ctx)
		if err != nil {
			return err
		}
		geq.sql = prev
	}
	return nil
}

func (geq *GnreEmissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GnreEmission, error) {
	var (
		nodes       = []*GnreEmission{}
		withFKs     = geq.withFKs
		_spec       = geq.querySpec()
		loadedTypes = [1]bool{
			geq.withEmission != nil,
		}
	)
	if geq.withEmission != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, gnreemission.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GnreEmission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GnreEmission{config: geq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, geq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := geq.withEmission; query != nil {
		if err := geq.loadEmission(ctx, query, nodes, nil,
			func(n *GnreEmission, e *Emission) { n.Edges.Emission = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (geq *GnreEmissionQuery) loadEmission(ctx context.Context, query *EmissionQuery, nodes []*GnreEmission, init func(*GnreEmission), assign func(*GnreEmission, *Emission)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GnreEmission)
	for i := range nodes {
		if nodes[i].emission_gnre_emission == nil {
			continue
		}
		fk := *nodes[i].emission_gnre_emission
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(emission.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "emission_gnre_emission" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (geq *GnreEmissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := geq.querySpec()
	_spec.Node.Columns = geq.ctx.Fields
	if len(geq.ctx.Fields) > 0 {
		_spec.Unique = geq.ctx.Unique != nil && *geq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, geq.driver, _spec)
}

func (geq *GnreEmissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(gnreemission.Table, gnreemission.Columns, sqlgraph.NewFieldSpec(gnreemission.FieldID, field.TypeUUID))
	_spec.From = geq.sql
	if unique := geq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if geq.path != nil {
		_spec.Unique = true
	}
	if fields := geq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gnreemission.FieldID)
		for i := range fields {
			if fields[i] != gnreemission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := geq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := geq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := geq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := geq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (geq *GnreEmissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(geq.driver.Dialect())
	t1 := builder.Table(gnreemission.Table)
	columns := geq.ctx.Fields
	if len(columns) == 0 {
		columns = gnreemission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if geq.sql != nil {
		selector = geq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if geq.ctx.Unique != nil && *geq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range geq.predicates {
		p(selector)
	}
	for _, p := range geq.order {
		p(selector)
	}
	if offset := geq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := geq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GnreEmissionGroupBy is the group-by builder for GnreEmission entities.
type GnreEmissionGroupBy struct {
	selector
	build *GnreEmissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gegb *GnreEmissionGroupBy) Aggregate(fns ...AggregateFunc) *GnreEmissionGroupBy {
	gegb.fns = append(gegb.fns, fns...)
	return gegb
}

// Scan applies the selector query and scans the result into the given value.
func (gegb *GnreEmissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gegb.build.ctx, ent.OpQueryGroupBy)
	if err := gegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GnreEmissionQuery, *GnreEmissionGroupBy](ctx, gegb.build, gegb, gegb.build.inters, v)
}

func (gegb *GnreEmissionGroupBy) sqlScan(ctx context.Context, root *GnreEmissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gegb.fns))
	for _, fn := range gegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gegb.flds)+len(gegb.fns))
		for _, f := range *gegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GnreEmissionSelect is the builder for selecting fields of GnreEmission entities.
type GnreEmissionSelect struct {
	*GnreEmissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ges *GnreEmissionSelect) Aggregate(fns ...AggregateFunc) *GnreEmissionSelect {
	ges.fns = append(ges.fns, fns...)
	return ges
}

// Scan applies the selector query and scans the result into the given value.
func (ges *GnreEmissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ges.ctx, ent.OpQuerySelect)
	if err := ges.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GnreEmissionQuery, *GnreEmissionSelect](ctx, ges.GnreEmissionQuery, ges, ges.inters, v)
}

func (ges *GnreEmissionSelect) sqlScan(ctx context.Context, root *GnreEmissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ges.fns))
	for _, fn := range ges.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ges.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ges.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
