// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessLog is the predicate function for accesslog builders.
type AccessLog func(*sql.Selector)

// Clients is the predicate function for clients builders.
type Clients func(*sql.Selector)

// Emission is the predicate function for emission builders.
type Emission func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// GnreEmission is the predicate function for gnreemission builders.
type GnreEmission func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
